name: paperEnv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.2
  - pytorch-cuda=11.7
  - pytorch=1.13.1
  - pip:
      - auto_mix_prep==0.2.0
      - click==8.1.7
      - einops==0.7.0
      - gensim==4.3.2
      - ipdb==0.13.13
      - matplotlib==3.8.1
      - more_itertools==10.2.0
      - numpy==1.26.4

      # Added jupyter notebook
      - jupyterlab>=4.2.5
      - notebook>=7.2.2
      
      # To utilize depracated 'tri', 'triu' and 'tril'
      - scipy<=1.12.0
      - openai==1.14.2
      - pandas==1.5.3
      - rich==13.7.1
      - sympy==1.12
      - tomlkit==0.12.4
      # To utilize split_torch_state_dict_into_shards
      - huggingface-hub>=0.23.0
      - tqdm==4.66.3
      # Removed exact dependency to allow for dependency adjustment
      - transformer_lens

      # Removed exact dependency to allow for dependency adjustment
      - transformers

      # Added missing dependency
      - pytest==8.3.4
